---
- name: restart postfix
  service:
    # See https://salsa.debian.org/postfix-team/postfix-dev/-/blob/debian/bullseye/debian/README.Debian
    name: postfix@-
    state: restarted

- name: restart dovecot
  service:
    name: dovecot
    state: restarted
